import { api, query } from './client';
import { session } from './session';
import type { Alert, AlertPreferences, AuthResponse, CommunityImpact, Coordinate, FloodReportResult, IncidentDetail, IncidentSeverity, IncidentType, LocationResult, MapIncidentFeed, MediaCompletion, MediaUploadAuthorization, NavigationSession, NotificationPreferences, OfficialWarning, RoutePreview, SavedPlace, User } from './types';

export const authApi = { async login(email: string, password: string) { const result = await api<AuthResponse>('/auth/login', { method: 'POST', body: { email, password }, retry: false }); session.save(result); return result; }, async register(displayName: string, email: string, password: string) { const result = await api<AuthResponse>('/auth/register', { method: 'POST', body: { displayName, email, password }, retry: false }); session.save(result); return result; }, me: () => api<User>('/me'), logout: async () => { try { await api<void>('/auth/logout', { method: 'POST', retry: false }); } finally { session.clear(); } } };
export const incidentsApi = { map: (bounds: { north: number; south: number; east: number; west: number; updatedSince?: string; limit?: number; incidentTypes?: string }) => api<MapIncidentFeed>(`/map/incidents${query(bounds)}`), detail: (id: string) => api<IncidentDetail>(`/incidents/${encodeURIComponent(id)}`), confirm: (id: string) => api(`/incidents/${encodeURIComponent(id)}/confirm`, { method: 'POST' }) };
export const reportsApi = { create: (input: { reportType: IncidentType; longitude: number; latitude: number; locationName: string; description: string; observedSeverity: IncidentSeverity; occurredAt?: string }) => api<FloodReportResult>('/flood-reports', { method: 'POST', body: input }) };
export const mediaApi = { authorize: (input: { reportId: string; contentType: string; byteSize: number }) => api<MediaUploadAuthorization>('/media/uploads', { method: 'POST', body: input }), complete: (id: string) => api<MediaCompletion>(`/media/${encodeURIComponent(id)}/complete`, { method: 'POST' }), upload: async (authorization: MediaUploadAuthorization['upload'], file: Blob) => { const response = await fetch(authorization.url, { method: authorization.method, headers: authorization.headers, body: file }); if (!response.ok) throw new Error('Upload failed') } };
export const locationsApi = { search: (q: string, proximity?: Coordinate) => api<LocationResult[]>(`/locations/search${query({ q, lat: proximity?.latitude, lng: proximity?.longitude })}`), resolve: (id: string) => api<LocationResult>(`/locations/${encodeURIComponent(id)}`), reverse: (point: Coordinate) => api<LocationResult>(`/locations/reverse${query({ lat: point.latitude, lng: point.longitude })}`) };
export const routesApi = { preview: (origin: Coordinate, destination: Coordinate, travelMode: 'DRIVING' | 'TRANSIT' | 'CYCLING' | 'WALKING' = 'DRIVING') => api<RoutePreview>('/routes/preview', { method: 'POST', body: { origin, destination, travelMode } }) };
export const navigationApi = { start: (input: { origin: Coordinate; destination: Coordinate; travelMode: 'DRIVING' | 'TRANSIT' | 'CYCLING' | 'WALKING'; route: Pick<RoutePreview['routes'][number], 'id' | 'geometry' | 'distanceMeters' | 'durationSeconds'> }) => api<NavigationSession>('/navigation/sessions', { method: 'POST', body: input }), get: (id: string) => api<NavigationSession>(`/navigation/sessions/${encodeURIComponent(id)}`), stop: (id: string) => api<void>(`/navigation/sessions/${encodeURIComponent(id)}`, { method: 'DELETE' }) };
export const demoApi = { triggerHazard: () => api<{ activated: true; incidentId: string; message: string }>('/demo/trigger-hazard', { method: 'POST', retry: false }) };
export const warningsApi = { active: () => api<{ data: OfficialWarning[] }>('/official-warnings?active=true&pageSize=5'), detail: (id: string) => api<OfficialWarning>(`/official-warnings/${encodeURIComponent(id)}`) };
export const savedPlacesApi = { list: () => api<{ data: SavedPlace[] }>('/saved-places?pageSize=50'), detail: (id: string) => api<SavedPlace>(`/saved-places/${encodeURIComponent(id)}`), create: (body: Partial<SavedPlace> & Coordinate) => api<SavedPlace>('/saved-places', { method: 'POST', body }), update: (id: string, body: Partial<SavedPlace> & Partial<Coordinate>) => api<SavedPlace>(`/saved-places/${encodeURIComponent(id)}`, { method: 'PATCH', body }), remove: (id: string) => api<void>(`/saved-places/${encodeURIComponent(id)}`, { method: 'DELETE' }) };
export const alertPreferencesApi = { get: () => api<AlertPreferences>('/alert-preferences'), update: (body: AlertPreferences) => api<AlertPreferences>('/alert-preferences', { method: 'PATCH', body }) };
export const notificationApi = { getPreferences: () => api<NotificationPreferences>('/notification-preferences'), updatePreferences: (body: Partial<Record<'appPushEnabled' | 'smsEnabled' | 'whatsappEnabled', boolean>>) => api<NotificationPreferences>('/notification-preferences', { method: 'PATCH', body }), devices: (body: { token: string; platform: string }) => api('/devices', { method: 'POST', body }), revokeDevice: (id: string) => api<void>(`/devices/${encodeURIComponent(id)}`, { method: 'DELETE' }), startPhoneVerification: (body: { phoneNumber: string }) => api<{ expiresAt: string; destination: string; purpose: string }>('/phone/verification/start', { method: 'POST', body }), confirmPhoneVerification: (body: { code: string }) => api<{ verified: true; destination: string; purpose: string }>('/phone/verification/confirm', { method: 'POST', body }), startWhatsAppVerification: (body: { phoneNumber: string }) => api<{ expiresAt: string; destination: string; purpose: string }>('/whatsapp/connection/start', { method: 'POST', body }), confirmWhatsAppVerification: (body: { code: string }) => api<{ verified: true; destination: string; purpose: string }>('/whatsapp/connection/confirm', { method: 'POST', body }), disconnectWhatsApp: () => api<void>('/whatsapp/connection', { method: 'DELETE' }) };
export const alertsApi = { list: (page = 1) => api<{ data: Alert[]; meta?: { hasNextPage?: boolean } }>(`/alerts?page=${page}&pageSize=20`), detail: (id: string) => api<Alert>(`/alerts/${encodeURIComponent(id)}`), read: (id: string) => api<void>(`/alerts/${encodeURIComponent(id)}/read`, { method: 'POST' }), readAll: () => api<{ updatedCount: number }>('/alerts/read-all', { method: 'POST' }) };
export const profileApi = { impact: () => api<CommunityImpact>('/me/community-impact') };
