import { useCallback, useEffect, useState } from 'react'
import { incidentsApi, warningsApi } from '../../api/services'
import type { IncidentDetail, MapIncident, OfficialWarning } from '../../api/types'
import type { Navigate } from '../../types'
import { BottomNav } from '../navigation/BottomNav'
import { Icon } from '../ui/Icon'
import { ScreenButton } from '../ui/ScreenButton'
import { SearchBar, WarningBanner } from './MapControls'

type Viewport = { north: number; south: number; east: number; west: number; limit: number }
function viewport(point: { latitude: number; longitude: number }): Viewport { return { north: Math.min(90, point.latitude + 0.06), south: Math.max(-90, point.latitude - 0.06), east: Math.min(180, point.longitude + 0.08), west: Math.max(-180, point.longitude - 0.08), limit: 100 } }
function markerPosition(incident: MapIncident, bounds: Viewport): { left: string; top: string } { const longitudeRange = Math.max(0.0001, bounds.east - bounds.west); const latitudeRange = Math.max(0.0001, bounds.north - bounds.south); const left = Math.min(94, Math.max(6, ((incident.coordinates.longitude - bounds.west) / longitudeRange) * 100)); const top = Math.min(86, Math.max(8, ((bounds.north - incident.coordinates.latitude) / latitudeRange) * 100)); return { left: `${left}%`, top: `${top}%` } }
function IncidentSheet({ incident, onClose, onConfirmed }: { incident: IncidentDetail; onClose: () => void; onConfirmed: () => void }) { const [confirming, setConfirming] = useState(false); const [error, setError] = useState(''); const confirm = async () => { setConfirming(true); setError(''); try { await incidentsApi.confirm(incident.id); onConfirmed() } catch { setError('You must be signed in, and this incident may be on cooldown.') } finally { setConfirming(false) } }; return <div className="incident-detail-backdrop" role="presentation"><section className="incident-detail-sheet" role="dialog" aria-modal="true" aria-labelledby="incident-detail-title"><ScreenButton className="alert-detail-close" onClick={onClose} ariaLabel="Close incident">×</ScreenButton><span className="settings-kicker">{incident.sourceType}</span><h2 id="incident-detail-title">{incident.locationName}</h2><p>{incident.description}</p><div className="incident-detail-meta"><span>{incident.confidence.label} confidence</span><span>{incident.confirmationCount} confirmations</span><span>{incident.photoCount} photos</span></div>{error && <p className="auth-error" role="alert">{error}</p>}<ScreenButton className="settings-primary" disabled={confirming || incident.status !== 'ACTIVE'} onClick={confirm}>{confirming ? 'Confirming…' : 'Confirm this incident'}</ScreenButton><ScreenButton className="secondary-action" onClick={onClose}>Close</ScreenButton></section></div> }

export function HomeScreen({ navigate }: { navigate: Navigate }) {
  const [incidents, setIncidents] = useState<MapIncident[]>([]); const [warning, setWarning] = useState<OfficialWarning>(); const [selected, setSelected] = useState<IncidentDetail | null>(null); const [bounds, setBounds] = useState<Viewport>(); const [locationReady, setLocationReady] = useState(false); const [error, setError] = useState('')
  const load = useCallback(() => { if (!navigator.geolocation) { setError('Location access is not available in this browser.'); return }; navigator.geolocation.getCurrentPosition(async (position) => { const point = { latitude: position.coords.latitude, longitude: position.coords.longitude }; const nextBounds = viewport(point); setBounds(nextBounds); setLocationReady(true); try { const [feed, activeWarnings] = await Promise.all([incidentsApi.map(nextBounds), warningsApi.active()]); setIncidents(feed.data); setWarning(activeWarnings.data[0]) } catch { setError('Live flood data is temporarily unavailable.') } }, () => setError('Allow location access to load nearby flood hazards.'), { enableHighAccuracy: false, timeout: 10000, maximumAge: 60_000 }) }, [])
  useEffect(() => { load() }, [load])
  const openIncident = (id: string) => { incidentsApi.detail(id).then(setSelected).catch(() => setError('Incident details are temporarily unavailable.')) }
  return <main className="screen-shell map-shell" aria-label="FloodLine home map"><div className="map-image" /><div className="map-wash" /><div className="home-content"><div className="map-top-controls"><SearchBar onClick={() => navigate('route-search', { sheet: true })} /><ScreenButton className="locate-button" ariaLabel="Use current location" onClick={load}><Icon name="locate.svg" /></ScreenButton></div><div className="warning-wrap"><WarningBanner warning={warning} /></div><div className="map-open-space">{bounds && incidents.map((incident) => <ScreenButton key={incident.id} className="severity-marker" style={markerPosition(incident, bounds)} title="Open incident" onClick={() => openIncident(incident.id)}><span className="severity-dot"><Icon name={incident.severity === 'SEVERE' ? 'severe.svg' : 'warning.svg'} /></span><span className="severity-label">{incident.severity}</span></ScreenButton>)}{!locationReady && <div className="map-location-prompt"><p>Use your location to see nearby flood incidents.</p><ScreenButton onClick={load}>Load nearby hazards</ScreenButton></div>}{error && <p className="auth-error map-error" role="alert">{error}</p>}<ScreenButton className="plan-route-pill" onClick={() => navigate('route-search', { sheet: true })}><Icon name="route.svg" /><strong>Plan Safe Route</strong></ScreenButton></div></div><BottomNav navigate={navigate} />{selected && <IncidentSheet incident={selected} onClose={() => setSelected(null)} onConfirmed={() => { setSelected(null); load() }} />}</main>
}
