import { useEffect, useState } from 'react'
import { locationsApi, mediaApi, reportsApi } from '../../api/services'
import type { Coordinate, IncidentSeverity, IncidentType } from '../../api/types'
import type { Navigate } from '../../types'
import { Icon } from '../ui/Icon'
import { ScreenButton } from '../ui/ScreenButton'
import { LiveMap } from '../map/LiveMap'
import { ReportFooter, ReportHeader, ReportStepIntro, ReportTypeCard, SeverityCard, type ReportKind, type ReportStep } from './ReportPrimitives'

const reportKinds: Array<ReportKind & { reportType: IncidentType }> = [
  { id: 'flooded-road', label: 'Flooded Road', icon: 'report-flooded-road.svg', reportType: 'SEVERE_FLOODING' },
  { id: 'road-blocked', label: 'Road Blocked', icon: 'report-road-blocked.svg', reportType: 'BLOCKED_ROAD' },
  { id: 'blocked-drain', label: 'Blocked Drain', icon: 'report-blocked-drain.svg', reportType: 'BLOCKED_DRAIN' },
]
const severityOptions: Array<{ id: string; label: string; tone: string; description: string; value: IncidentSeverity }> = [
  { id: 'minor', label: 'Minor', tone: 'minor', description: 'Water below ankle level. Vehicles moving normally.', value: 'LOW' },
  { id: 'moderate', label: 'Moderate', tone: 'moderate', description: 'Water above ankle level. Vehicles are passing carefully.', value: 'MODERATE' },
  { id: 'severe', label: 'Severe', tone: 'severe', description: 'Water near tyre level. Small cars may not pass safely.', value: 'HIGH' },
  { id: 'impassable', label: 'Impassable', tone: 'impassable', description: 'Road cannot be used safely. Vehicles are turning back or stranded.', value: 'SEVERE' },
]

function locationError(code?: number): string {
  if (code === 1) return 'Location permission is blocked. Allow it in your browser settings, then try again.'
  if (code === 2) return 'Your device could not find a location. Check location services and try again.'
  return 'We could not find your location. Check your device settings and try again.'
}

function ReportTypeStep({ selected, onSelect, onContinue, onBack }: { selected: string | null; onSelect: (id: string) => void; onContinue: () => void; onBack: () => void }) { return <><ReportHeader title="Report Condition" onBack={onBack} /><section className="report-step-content"><ReportStepIntro title="What are you seeing?" copy="Help people nearby understand what's happening." /><div className="report-type-grid">{reportKinds.map((kind) => <ReportTypeCard key={kind.id} kind={kind} selected={selected === kind.id} onSelect={() => onSelect(kind.id)} />)}</div></section><ReportFooter onClick={onContinue} disabled={!selected} /></> }
function SeverityStep({ selected, onSelect, onContinue, onBack }: { selected: string | null; onSelect: (id: string) => void; onContinue: () => void; onBack: () => void }) { return <><ReportHeader title="Severity" onBack={onBack} /><section className="report-step-content"><ReportStepIntro title="How bad is it?" copy="Choose the closest description so drivers can understand the risk." /><div className="report-severity-list">{severityOptions.map((option) => <SeverityCard key={option.id} {...option} selected={selected === option.id} onSelect={() => onSelect(option.id)} />)}</div></section><ReportFooter onClick={onContinue} disabled={!selected} /></> }

function LocationStep({ location, landmark, coordinate, onUseCurrent, onLandmark, onContinue, onBack, locating, error }: { location: string | null; landmark: string; coordinate: Coordinate | null; onUseCurrent: () => void; onLandmark: (value: string) => void; onContinue: () => void; onBack: () => void; locating: boolean; error: string }) { return <><ReportHeader title="Location" onBack={onBack} /><section className="report-step-content"><ReportStepIntro title="Where is the flooding?" copy="Place the report where the flooding is happening. Your location is only used to map the report." /><div className="report-location-map"><LiveMap className="report-live-map" center={coordinate ?? undefined} />{coordinate ? <span className="report-map-pin"><Icon name="report-location-pin.svg" /></span> : <div className="report-map-empty"><span className="location-status-icon"><Icon name="locate.svg" /></span><strong>Location not set</strong><small>Use your current location to place the report.</small></div>}<div className={`report-location-map-status ${coordinate ? 'is-ready' : ''}`}><span className="location-status-dot" /><div><strong>{coordinate ? 'Location ready' : 'Waiting for location'}</strong><small>{coordinate ? (location || 'Your current position') : 'The map will center on your position.'}</small></div></div></div><ScreenButton className="location-suggestion" onClick={onUseCurrent} disabled={locating} ariaBusy={locating}><span className="location-status-icon"><Icon name="locate.svg" /></span><span className="location-action-copy"><strong>{locating ? 'Finding your location…' : coordinate ? 'Update current location' : 'Use my current location'}</strong><small>{locating ? 'Waiting for device permission' : coordinate ? 'Move the report pin if the road has changed.' : 'Your browser will ask for permission.'}</small></span><span className="location-action-arrow" aria-hidden="true">›</span></ScreenButton><label className="report-landmark-label">Approximate address<input className="report-landmark-input" value={location ?? ''} readOnly placeholder="Your approximate address appears here" /></label><label className="report-landmark-label">Nearby landmark (optional)<input className="report-landmark-input" value={landmark} onChange={(event) => onLandmark(event.target.value)} placeholder="e.g. opposite the fuel station" /></label>{error && <p className="auth-error" role="alert">{error}</p>}</section><ReportFooter label="Confirm location" onClick={onContinue} disabled={!coordinate} /></> }

function EvidenceStep({ note, file, onNote, onFile, onContinue, onSkip, onBack }: { note: string; file: File | null; onNote: (value: string) => void; onFile: (file: File | null) => void; onContinue: () => void; onSkip: () => void; onBack: () => void }) { return <><ReportHeader title="Evidence" onBack={onBack} /><section className="report-step-content"><ReportStepIntro title="Show what's happening" copy="A photo helps others verify the report faster." /><div className="report-photo-actions"><label className="report-photo-button"><Icon name="report-camera.svg" /><strong>{file ? file.name : 'Choose a photo'}</strong><input className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => onFile(event.target.files?.[0] ?? null)} /></label>{file && <ScreenButton className="report-upload-button" onClick={() => onFile(null)}>Remove photo</ScreenButton>}</div><label className="report-note-label">Anything drivers should know?<textarea value={note} onChange={(event) => onNote(event.target.value)} maxLength={5000} /></label></section><ReportFooter onClick={onContinue} secondaryLabel="Skip for now" onSecondaryClick={onSkip} /></> }

function ConfirmStep({ kind, severity, location, note, file, onSubmit, onBack, submitting, error }: { kind: (ReportKind & { reportType: IncidentType }) | undefined; severity: string | null; location: string | null; note: string; file: File | null; onSubmit: () => void; onBack: () => void; submitting: boolean; error: string }) { return <><ReportHeader title="Confirm your report" onBack={onBack} /><section className="report-step-content report-confirm-content"><div className="report-confirm-icon"><Icon name="report-flooded-road.svg" /></div><h2>Flooding Reported</h2><p className="report-confirm-location">{location || 'Current location'}</p><div className="report-summary-card"><div><span>Condition</span><strong>{kind?.label || 'Flooded Road'}</strong></div><div><span>Severity</span><strong>{severity ? severityOptions.find((option) => option.id === severity)?.label : 'Not selected'}</strong></div><div><span>Details</span><strong>{note || 'No additional details'}</strong></div><div><span>Evidence</span><strong>{file ? file.name : '0 photos'}</strong></div></div><p className="report-privacy-copy">Your name and phone number won't be displayed publicly.</p>{error && <p className="auth-error" role="alert">{error}</p>}</section><ReportFooter label={submitting ? 'Submitting…' : 'Report Flooding'} onClick={onSubmit} disabled={submitting} /></> }
function SuccessStep({ onMap }: { onMap: () => void }) { return <section className="report-success-screen"><div className="report-success-icon"><Icon name="report-success.svg" /></div><h1>Your report is live</h1><p>People nearby can now see this hazard.</p><ScreenButton className="report-primary-button" onClick={onMap}>Back to live map</ScreenButton></section> }

export function ReportFlowScreen({ navigate }: { navigate: Navigate }) {
  const [step, setStep] = useState<ReportStep>('type'); const [kindId, setKindId] = useState<string | null>(null); const [severity, setSeverity] = useState<string | null>(null); const [location, setLocation] = useState<string | null>(null); const [coordinate, setCoordinate] = useState<Coordinate | null>(null); const [landmark, setLandmark] = useState(''); const [note, setNote] = useState(''); const [file, setFile] = useState<File | null>(null); const [locating, setLocating] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const kind = reportKinds.find((option) => option.id === kindId)
  useEffect(() => { if (!file || !file.type.startsWith('image/')) setFile(null) }, [file])
  const useCurrentLocation = () => { if (locating) return; if (!navigator.geolocation) { setError('Location access is not available in this browser.'); return }; setLocating(true); setError(''); navigator.geolocation.getCurrentPosition(async (position) => { const next = { longitude: position.coords.longitude, latitude: position.coords.latitude }; setCoordinate(next); try { const result = await locationsApi.reverse(next); setLocation(result.formattedAddress) } catch { setLocation('Current location') } finally { setLocating(false) } }, (positionError) => { setError(locationError(positionError.code)); setLocating(false) }, { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 }) }
  const submit = async () => { if (!kind || !severity || !coordinate) return; setSubmitting(true); setError(''); try { const selectedSeverity = severityOptions.find((option) => option.id === severity)?.value ?? 'MODERATE'; const result = await reportsApi.create({ reportType: kind.reportType, longitude: coordinate.longitude, latitude: coordinate.latitude, locationName: [location, landmark].filter(Boolean).join(' · ') || 'Current location', description: note.trim() || 'Flooding condition reported by a community member.', observedSeverity: selectedSeverity, occurredAt: new Date().toISOString() }); if (file) { const authorization = await mediaApi.authorize({ reportId: result.reportId, contentType: file.type, byteSize: file.size }); await mediaApi.upload(authorization.upload, file); await mediaApi.complete(authorization.media.id) }; setStep('success') } catch { setError('Couldn’t submit this report. Please try again.'); } finally { setSubmitting(false) } }
  const goBack = () => { if (step === 'type') navigate('home'); else if (step === 'severity') setStep('type'); else if (step === 'location') setStep('severity'); else if (step === 'evidence') setStep('location'); else if (step === 'confirm') setStep('evidence') }
  return <main className="screen-shell flow-shell report-shell" aria-label="Report a flood condition">{step === 'type' && <ReportTypeStep selected={kindId} onSelect={setKindId} onContinue={() => setStep('severity')} onBack={() => navigate('home')} />}{step === 'severity' && <SeverityStep selected={severity} onSelect={setSeverity} onContinue={() => setStep('location')} onBack={goBack} />}{step === 'location' && <LocationStep location={location} landmark={landmark} coordinate={coordinate} onUseCurrent={useCurrentLocation} onLandmark={setLandmark} onContinue={() => setStep('evidence')} onBack={goBack} locating={locating} error={error} />}{step === 'evidence' && <EvidenceStep note={note} file={file} onNote={setNote} onFile={setFile} onContinue={() => setStep('confirm')} onSkip={() => setStep('confirm')} onBack={goBack} />}{step === 'confirm' && <ConfirmStep kind={kind} severity={severity} location={location} note={note} file={file} onSubmit={submit} onBack={goBack} submitting={submitting} error={error} />}{step === 'success' && <SuccessStep onMap={() => navigate('home')} />}</main>
}
