import {
  ArrowLeft,
  Bell,
  Bike,
  BriefcaseBusiness,
  Building2,
  BusFront,
  Camera,
  Car,
  Check,
  CircleAlert,
  CircleCheck,
  Construction,
  Droplets,
  History,
  Home,
  Image,
  LocateFixed,
  Map,
  MapPin,
  Megaphone,
  Navigation,
  PersonStanding,
  Route,
  Search,
  TriangleAlert,
  UserRound,
  Waves,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { AssetName } from '../../types'

const iconMap: Record<AssetName, LucideIcon> = {
  'alerts-nav.svg': Bell,
  'back.svg': ArrowLeft,
  'bike.svg': Bike,
  'bus.svg': BusFront,
  'car.svg': Car,
  'current-location.svg': LocateFixed,
  'hazard-marker.svg': TriangleAlert,
  'home.svg': Home,
  'locate.svg': LocateFixed,
  'map-nav.svg': Map,
  'profile-nav.svg': UserRound,
  'recent.svg': History,
  'report-nav.svg': Megaphone,
  'route-nav.svg': Route,
  'route-path.svg': Route,
  'route.svg': Navigation,
  'search.svg': Search,
  'severe.svg': TriangleAlert,
  'walk.svg': PersonStanding,
  'warning.svg': CircleAlert,
  'work.svg': BriefcaseBusiness,
  'route-results-back.svg': ArrowLeft,
  'route-results-car.svg': Car,
  'route-results-bus.svg': BusFront,
  'route-results-bike.svg': Bike,
  'route-results-walk.svg': PersonStanding,
  'route-results-path.svg': Route,
  'route-results-hazard.svg': TriangleAlert,
  'report-back.svg': ArrowLeft,
  'report-flooded-road.svg': Waves,
  'report-road-blocked.svg': Construction,
  'report-blocked-drain.svg': Droplets,
  'report-building-flooding.svg': Building2,
  'report-electrical.svg': Zap,
  'report-road-clear.svg': CircleCheck,
  'report-selected-primary.svg': Check,
  'report-selected-secondary.svg': Check,
  'report-location-pin.svg': MapPin,
  'report-camera.svg': Camera,
  'report-photo.png': Image,
  'report-photo-remove.svg': X,
  'report-success.svg': CircleCheck,
}

export function Icon({ name, className = '' }: { name: AssetName; className?: string }) {
  const IconComponent = iconMap[name]
  return <IconComponent className={`icon ${className}`} aria-hidden="true" strokeWidth={1.9} />
}
