import { useState, type ReactNode } from 'react'
import { Icon } from '../ui/Icon'
import { ScreenButton } from '../ui/ScreenButton'
import type { AssetName } from '../../types'
import type { Coordinate, RouteCandidate } from '../../api/types'
import { LiveMap } from '../map/LiveMap'

export function FlowHeader({ title, onBack }: { title: string; onBack: () => void }) { return <header className="flow-header"><ScreenButton className="back-button" onClick={onBack} ariaLabel="Go back"><Icon name="back.svg" /></ScreenButton><h1>{title}</h1></header> }
export function TimelineRail({ connected }: { connected: boolean }) { return <div className={`timeline-rail ${connected ? 'is-connected' : ''}`} aria-hidden="true"><span className="timeline-start" />{connected && <><span className="timeline-line" /><Icon name="current-location.svg" /></>}</div> }
export function RecentPlace({ title, subtitle }: { title: string; subtitle: string }) { return <ScreenButton className="place-row"><span className="place-icon"><Icon name="recent.svg" /></span><span className="place-copy"><strong>{title}</strong><small>{subtitle}</small></span></ScreenButton> }
export function SavedPlace({ title, icon }: { title: string; icon: AssetName }) { return <ScreenButton className="place-row"><span className="place-icon"><Icon name={icon} /></span><span className="place-copy"><strong>{title}</strong></span></ScreenButton> }
export function ModeTab({ icon, active }: { icon: AssetName; active?: boolean }) { return <ScreenButton className={`mode-tab ${active ? 'is-active' : ''}`}><Icon name={icon} /></ScreenButton> }
export function RouteFlowCanvas({ children, routeUpdated = false, noOverlay = false, onClose, destinationLabel = 'destination', durationSeconds, distanceMeters, updateMessage, routeGeometry, routeCenter, statusLabel = 'Alternative route active' }: { children: ReactNode; routeUpdated?: boolean; noOverlay?: boolean; onClose?: () => void; destinationLabel?: string; durationSeconds?: number; distanceMeters?: number; updateMessage?: string; routeGeometry?: RouteCandidate['geometry']; routeCenter?: Coordinate; statusLabel?: string }) { const durationLabel = durationSeconds ? `${Math.max(1, Math.round(durationSeconds / 60))} min` : 'Route active'; const distanceLabel = distanceMeters ? `${(distanceMeters / 1000).toFixed(1)} km` : ''; const routeGeometries = routeGeometry ? [{ id: 'active-navigation-route', geometry: routeGeometry, recommended: true }] : []; return <main className="screen-shell route-state-shell" aria-label="Live route monitoring"><LiveMap className="route-state-live-map" center={routeCenter} routeGeometries={routeGeometries} /><div className="route-state-wash" /><div className="route-state-topbar"><ScreenButton className="map-close-button" ariaLabel="Close route" onClick={onClose}>×</ScreenButton><div className="route-summary-card"><span>To: {destinationLabel}</span><strong>{durationLabel} {distanceLabel && <em>· {distanceLabel}</em>}</strong></div></div><div className="route-state-pills"><span className="active-route-pill">{statusLabel}</span><span className="monitoring-pill"><i />FloodLine monitoring live</span></div>{routeUpdated && <div className="route-updated-banner"><span className="route-updated-icon">↗</span><div><strong>Route updated</strong><small>{updateMessage || 'A lower reported flood-risk route is available.'}</small></div></div>}{!noOverlay && <div className="route-state-backdrop" />}{children}</main> }
export function SheetHandle() { return <div className="sheet-handle" aria-hidden="true" /> }
export function HazardItem({ tone, title, severity, detail }: { tone: 'severe' | 'moderate'; title: string; severity: string; detail: string }) { return <div className={`hazard-item hazard-item-${tone}`}><span className="hazard-item-icon"><Icon name={tone === 'severe' ? 'severe.svg' : 'warning.svg'} /></span><span className="hazard-item-copy"><strong>{title}</strong><span>{severity}</span><small>{detail}</small></span></div> }
export function ActiveRouteSheet({ durationSeconds, distanceMeters, onStop }: { durationSeconds?: number; distanceMeters?: number; onStop?: () => void }) { const [collapsed, setCollapsed] = useState(false); const durationLabel = durationSeconds ? `${Math.max(1, Math.round(durationSeconds / 60))} min` : 'Route active'; const distanceLabel = distanceMeters ? `${(distanceMeters / 1000).toFixed(1)} km` : ''; return <section className={`route-state-sheet active-sheet ${collapsed ? 'is-collapsed' : ''}`}><SheetHandle /><div className="active-sheet-header"><div className="active-heading"><span className="success-check">✓</span><div><h1>Route Active</h1><p>{durationLabel} {distanceLabel && `· ${distanceLabel}`}</p></div></div><ScreenButton className="collapse-button" ariaLabel={collapsed ? 'Expand route status' : 'Collapse route status'} onClick={() => setCollapsed((value) => !value)}>⌃</ScreenButton></div>{!collapsed && <><div className="active-status-card">Proceeding with caution. Hazard monitoring active.</div>{onStop && <ScreenButton className="secondary-action" onClick={onStop}>End navigation</ScreenButton>}</>}</section> }
