import { useEffect, useState } from 'react'
import { locationsApi, routesApi, savedPlacesApi } from '../../api/services'
import type { Coordinate, LocationResult, SavedPlace } from '../../api/types'
import type { Navigate } from '../../types'
import { Icon } from '../ui/Icon'
import { ScreenButton } from '../ui/ScreenButton'
import { FlowHeader, TimelineRail } from './RoutePrimitives'
import { saveRoutePlan } from './route-state'

export function RouteSearchScreen({ navigate, onBack, sheet = false }: { navigate: Navigate; onBack: () => void; sheet?: boolean }) {
  const [origin, setOrigin] = useState<Coordinate | null>(null); const [originLabel, setOriginLabel] = useState(''); const [destination, setDestination] = useState<LocationResult | null>(null); const [destinationQuery, setDestinationQuery] = useState(''); const [results, setResults] = useState<LocationResult[]>([]); const [savedPlaces, setSavedPlaces] = useState<SavedPlace[]>([]); const [searching, setSearching] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { savedPlacesApi.list().then((response) => setSavedPlaces(response.data)).catch(() => undefined) }, [])
  useEffect(() => { if (destinationQuery.trim().length < 2) { setResults([]); return }; const timer = window.setTimeout(() => { setSearching(true); locationsApi.search(destinationQuery.trim()).then(setResults).catch(() => setError('Location search is unavailable right now.')).finally(() => setSearching(false)) }, 300); return () => window.clearTimeout(timer) }, [destinationQuery])
  const useCurrentLocation = () => { if (!navigator.geolocation) { setError('Location access is not available in this browser.'); return }; setError(''); navigator.geolocation.getCurrentPosition(async (position) => { const point = { longitude: position.coords.longitude, latitude: position.coords.latitude }; setOrigin(point); try { setOriginLabel((await locationsApi.reverse(point)).formattedAddress) } catch { setOriginLabel('Current location') } }, () => setError('Allow location access to plan a route from here.'), { enableHighAccuracy: true, timeout: 10000, maximumAge: 30_000 }) }
  const submit = async () => { if (!origin || !destination) return; setLoading(true); setError(''); try { const preview = await routesApi.preview(origin, destination.coordinates); saveRoutePlan({ origin, destination: destination.coordinates, destinationLabel: destination.formattedAddress, travelMode: 'DRIVING', preview }); navigate('route-results') } catch { setError('Routes are temporarily unavailable. Please try again.') } finally { setLoading(false) } }
  return <main className={`screen-shell flow-shell ${sheet ? 'sheet-screen' : ''}`} aria-label="Choose a route destination"><FlowHeader title="Where are you going?" onBack={onBack} /><section className={`destination-form ${origin ? 'has-current-location' : ''}`}><TimelineRail connected={Boolean(origin)} /><div className="destination-fields">{origin ? <div className="current-location-card selected-location-card"><span>From</span><strong>{originLabel || 'Current location'}</strong></div> : <ScreenButton className="location-entry" onClick={useCurrentLocation}><Icon name="locate.svg" /><span>Use current location</span></ScreenButton>}<label className="destination-input"><input autoFocus={Boolean(origin)} value={destinationQuery} onChange={(event) => { setDestinationQuery(event.target.value); setDestination(null) }} placeholder="Search road, landmark or place" /><Icon name="search.svg" /></label></div></section>{error && <p className="auth-error route-search-error" role="alert">{error}</p>}<section className="places-section">{searching && <p className="settings-state">Searching…</p>}{!searching && destinationQuery.length >= 2 && <div className="place-list">{results.map((result) => <button className="route-location-result" type="button" key={result.providerPlaceId} onClick={() => { setDestination(result); setDestinationQuery(result.formattedAddress); setResults([]) }}><strong>{result.name}</strong><small>{result.formattedAddress}</small></button>)}</div>}{!destinationQuery && <><h2>Saved places</h2><div className="place-list">{savedPlaces.map((place) => <button className="route-location-result" type="button" key={place.id} onClick={() => { setDestination({ providerPlaceId: place.providerPlaceId || place.id, name: place.customLabel || place.type, formattedAddress: place.formattedAddress, coordinates: place.location }); setDestinationQuery(place.formattedAddress) }}><strong>{place.customLabel || place.type}</strong><small>{place.formattedAddress}</small></button>)}</div></>}</section><ScreenButton className="settings-primary route-search-submit" disabled={!origin || !destination || loading} onClick={submit}>{loading ? 'Finding routes…' : 'Show routes'}</ScreenButton></main>
}
